GET http://localhost:5175/games

###
GET http://localhost:5175/games/2

###
POST http://localhost:5175/games
Content-Type: application/json

{
    "name": "Test Game",
    "genreId": 4,
    "price": 30,
    "releaseDate": "2023-10-20"
}

###
PUT http://localhost:5175/games/2
Content-Type: application/json

{
    "name": "Example Name",
    "genreId": 3,
    "price": 20,
    "releaseDate": "2010-12-22"
}

###
DELETE  http://localhost:5175/games/4

###
GET http://localhost:5175/genres