GET http://localhost:5175/games

###
GET http://localhost:5175/games/4

###
POST http://localhost:5175/games
Content-Type: application/json

{
    "name": "Super Mario",
    "genre": "Platformer",
    "price": 59.99,
    "releaseDate": "2023-10-20"
}

###
PUT http://localhost:5175/games/5
Content-Type: application/json

{
    "name": "Example Name",
    "genre": "Plat",
    "price": 20,
    "releaseDate": "2010-12-22"
}

###
DELETE  http://localhost:5175/games/1